/*
 * The offline service worker, as a source string with a build-time hole for the
 * precache manifest. `renderServiceWorker` fills the hole; the precache
 * integration (`precache-integration.ts`) writes the result to `dist/sw.js` on
 * every build. Kept as a string (not a real module) because it ships verbatim to
 * the browser and must not go through the app's bundler.
 *
 * Strategy:
 *  - install: open a version-named cache and precache the whole Course.
 *  - activate: delete every other `ai101-` cache, then take control.
 *  - fetch (GET, same-origin only):
 *      navigations → cache first, network fallback, then the cached language
 *                    shell so an unknown deep link still renders offline.
 *      everything else → cache first, network fallback.
 */

import type { PrecacheManifest } from "./precache";

const TEMPLATE = `/* Generated by precache-integration.ts — do not edit. */
const VERSION = %VERSION%;
const CACHE_NAME = "ai101-" + VERSION;
const PRECACHE_URLS = %URLS%;
const SHELL_URL = %SHELL%;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME && key.startsWith("ai101-"))
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      caches.match(request, { ignoreSearch: true }).then((cached) => {
        if (cached) return cached;
        return fetch(request).catch(() =>
          caches.match(SHELL_URL).then((shell) => shell || caches.match("/")),
        );
      }),
    );
    return;
  }

  event.respondWith(
    caches
      .match(request, { ignoreSearch: true })
      .then((cached) => cached || fetch(request)),
  );
});
`;

/**
 * The language shell a failed offline navigation falls back to. Prefer the
 * caller's `preferredShell` (the default language's `/xx/` route); fall back to
 * the first precached `/xx/` route, then to `/`.
 */
function resolveShell(
  urls: readonly string[],
  preferredShell: string | undefined,
): string {
  if (preferredShell && urls.includes(preferredShell)) return preferredShell;
  return urls.find((u) => /^\/[a-z]{2}(-[a-z0-9]+)?\/$/i.test(u)) ?? "/";
}

export function renderServiceWorker(
  manifest: PrecacheManifest,
  opts: { preferredShell?: string } = {},
): string {
  const shell = resolveShell(manifest.urls, opts.preferredShell);
  // Use a replacer function so `$` sequences in the JSON never trigger
  // `String.prototype.replace`'s special-pattern handling.
  return TEMPLATE.replace("%VERSION%", () => JSON.stringify(manifest.version))
    .replace("%URLS%", () => JSON.stringify(manifest.urls))
    .replace("%SHELL%", () => JSON.stringify(shell));
}
